// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3OXJOsoDOHTihg-RNAnbqOJ4fHQUTrLg',
    appId: '1:200038183409:web:34d46a3190659c851b9450',
    messagingSenderId: '200038183409',
    projectId: 'dershaneapp-a9674',
    authDomain: 'dershaneapp-a9674.firebaseapp.com',
    storageBucket: 'dershaneapp-a9674.firebasestorage.app',
    measurementId: 'G-KR42G5M7D0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_YJ1pxB_PLORlHFtioLtoCBBmUBWSdYI',
    appId: '1:200038183409:android:1b3038233f3723eb1b9450',
    messagingSenderId: '200038183409',
    projectId: 'dershaneapp-a9674',
    storageBucket: 'dershaneapp-a9674.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuGxzhxS_rG4_gu1-ZPHGSJng5IvxExB8',
    appId: '1:200038183409:ios:0c06e2fd7e7b8e911b9450',
    messagingSenderId: '200038183409',
    projectId: 'dershaneapp-a9674',
    storageBucket: 'dershaneapp-a9674.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuGxzhxS_rG4_gu1-ZPHGSJng5IvxExB8',
    appId: '1:200038183409:ios:0c06e2fd7e7b8e911b9450',
    messagingSenderId: '200038183409',
    projectId: 'dershaneapp-a9674',
    storageBucket: 'dershaneapp-a9674.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3OXJOsoDOHTihg-RNAnbqOJ4fHQUTrLg',
    appId: '1:200038183409:web:6233871f597ae8e81b9450',
    messagingSenderId: '200038183409',
    projectId: 'dershaneapp-a9674',
    authDomain: 'dershaneapp-a9674.firebaseapp.com',
    storageBucket: 'dershaneapp-a9674.firebasestorage.app',
    measurementId: 'G-PEBYEYCP9N',
  );
}
